export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";

export const GET_FROM = "INPUTS/GET_FROM";
export const GET_TO = "INPUT/GET_TO";
export const GET_AIRPORT_TO_NAME = "INPUTS/GET_AIRPORT_TO_NAME";
export const GET_AIRPORT_NAME = "INPUTS/GET_AIRPORT_NAME";

export const CLEAR_AIRPORT_NAME = "INPUTS/CLEAR_AIRPORT_NAME";
export const CLEAR_AIRPORT_TO_NAME = "INPUTS/CLEAR_AIRPORT_TO_NAME";

export const TOGGLE_CALENDAR = "INPUTS/TOGGLE_CALENDAR";
export const SELECT_DEPARTURE_DAY = "INPUTS/SELECT_DEPARTURE_DAY";
export const SELECT_ARRIVAL_DAY = "INPUTS/SELECT_ARRIVAL_DAY";
export const SELECT_ONE_WAY = "INPUTS/SELECT_ONE_WAY";
export const CLEAR_DATES = "INPUTS/CLEAR_DATES";

export const CLEAR_AIRPORT_DATA = "AIRPORT_DATA/CLEAR_AIRPORT_DATA";
export const LOAD_AIRPORT_DATA = "AIRPORT_DATA/LOAD_AIRPORT_DATA";

export const CLEAR_AIRPORT_TO_DATA = "AIRPORT_DATA/CLEAR_AIRPORT_TO_DATA";
export const LOAD_AIRPORT_TO_DATA = "AIRPORT_DATA/LOAD_AIRPORT_TO_DATA";

export const GET_CURRENCY = "INPUTS/GET_CURRENCY";
export const GET_TICKET = "INPUTS/GET_TICKET";
export const CLEAR_TICKET = "INPUTS/CLEAR_TICKET";
export const LOAD_FLIGHT_DATA = "FLIGHTDATA/LOAD_FLIGHT_DATA";
export const CLICK_TO = "INPUTS/CLICK_TO";
export const CLICK_FROM = "INPUTS/CLICK_FROM";

export const GET_PASSENGER = "INPUTS/GET_PASSENGER";
export const PASSENGER_PANEL = "INPUTS/PASSENGER_PANEL";
export const PAGINATE_BY_PAGE = "INPUTS/PAGINATE_BY_PAGE";

export const SORT_FLIGHT_DATA = "FLIGHTDATA/SORT_FLIGHT_DATA";

export const TICKET_OPEN = "INPUTS/TICKET_OPEN";

export const WARNING = "APP/WARNING";
export const LOAD_MORE_FLIGHTS = "INPUTS/LOAD_MORE_FLIGHTS";
export const DIRECT_FLY = "INPUTS/DIRECT_FLY";
export const FLY_DETAILS_PANEL_TOGGLE = "INPUTS/FLY_DETAILS_PANEL_TOGGLE";
export const GET_DETAILS = "INPUTS/GET_DETAILS";
export const GET_SORT_DIRECTION = "FLIGHTDATA/GET_SORT_DIRECTION";
export const SORT_BY_DURATION = "FLIGHTDATA/SORT_BY_DURATION";
export const SORT_BY_DURATION_DESR = "FLIGHTDATA/SORT_BY_DURATION_DESR";
